repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: check-merge-conflict
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
            exclude: '.*\.eps'
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.6.2
      hooks:
          - id: prettier
            args:
                - --config-precedence=file-override
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
